#ifndef CGEN_H_
#define CGEN_H_

#include "base/core.h"
#include "base/gtype.h"
#include "base/hashes.h"
#include "dab/arr.h"
#include "dab/gvec.h"
#include "dab/heap.h"
#include "dab/hmap.h"
#include "dab/hset.h"
#include "dab/p1w.h"
#include "dab/p2w.h"
#include "dab/spec/d2w.h"
#include "list/dll.h"
#include "list/gdl.h"
#include "list/gsl.h"
#include "list/sll.h"
#include "list/spec/idl.h"
#include "list/spec/isl.h"
#include "tree/bn.h"
#include "tree/bs.h"
#include "tree/rbm.h"
#include "tree/rbs.h"
#include "tree/spec/gbs.h"
#include "tree/spec/grb.h"
#include "tree/spec/s2i.h"
#include "utils/io.h"
#include "utils/io.h"
#include "utils/str.h"

#endif  // CGEN_H_